Benchmark Pipeline
TIGER-AI-Lab/VideoGenHub pull request #23
Opened 2024-05-12 18:12 UTC by Richard5678

implemented benchmark pipeline and random prompt sampling

2024-05-13 05:58 UTC, vinesmsuic requested changes

2024-05-13 05:58 UTC, vinesmsuic commented on src/videogen_hub/benchmark/text_guided_t2v.py
> +def infer_text_guided_ig_bench(
should be VG instead of IG

2024-05-13 05:58 UTC, vinesmsuic commented on src/videogen_hub/benchmark/text_guided_t2v.py
> +    Performs inference on the VideonHub dataset using the provided text-guided video generation model.
typo

2024-05-14 01:20 UTC, Richard5678 commented on src/videogen_hub/benchmark/text_guided_t2v.py
> +    Performs inference on the VideonHub dataset using the provided text-guided video generation model.
What is the typo here?

2024-05-14 13:27 UTC, vinesmsuic approved these changes

2024-05-14 13:27 UTC, merged